import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        <Link href="/jsScroll">jsScroll</Link>
        <Link href="/cssScroll">cssScroll</Link>
        <Link href="/firewatch">firewatch</Link>
      </main>
    </>
  )
}
